/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConferenceRouteImport } from './routes/conference'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BookRouteImport } from './routes/book'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemStaffRouteImport } from './routes/system.staff'
import { Route as StaffNewRouteImport } from './routes/staff.new'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as BookConfirmationRouteImport } from './routes/book.confirmation'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceRoute = ConferenceRouteImport.update({
  id: '/conference',
  path: '/conference',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStaffRoute = SystemStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SystemRoute,
} as any)
const StaffNewRoute = StaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RoomsRoute,
} as any)
const BookConfirmationRoute = BookConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => BookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/book': typeof BookRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/gallery': typeof GalleryRoute
  '/guests': typeof GuestsRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/portal': typeof PortalRoute
  '/restaurant': typeof RestaurantRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/system': typeof SystemRouteWithChildren
  '/book/confirmation': typeof BookConfirmationRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/staff/new': typeof StaffNewRoute
  '/system/staff': typeof SystemStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/book': typeof BookRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/gallery': typeof GalleryRoute
  '/guests': typeof GuestsRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/portal': typeof PortalRoute
  '/restaurant': typeof RestaurantRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/system': typeof SystemRouteWithChildren
  '/book/confirmation': typeof BookConfirmationRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/staff/new': typeof StaffNewRoute
  '/system/staff': typeof SystemStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/book': typeof BookRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/conference': typeof ConferenceRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/gallery': typeof GalleryRoute
  '/guests': typeof GuestsRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/portal': typeof PortalRoute
  '/restaurant': typeof RestaurantRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/system': typeof SystemRouteWithChildren
  '/book/confirmation': typeof BookConfirmationRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/staff/new': typeof StaffNewRoute
  '/system/staff': typeof SystemStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/billing'
    | '/book'
    | '/calendar'
    | '/conference'
    | '/contact'
    | '/dining'
    | '/gallery'
    | '/guests'
    | '/login'
    | '/lookup'
    | '/portal'
    | '/restaurant'
    | '/rooms'
    | '/system'
    | '/book/confirmation'
    | '/rooms/$roomId'
    | '/staff/new'
    | '/system/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/billing'
    | '/book'
    | '/calendar'
    | '/conference'
    | '/contact'
    | '/dining'
    | '/gallery'
    | '/guests'
    | '/login'
    | '/lookup'
    | '/portal'
    | '/restaurant'
    | '/rooms'
    | '/system'
    | '/book/confirmation'
    | '/rooms/$roomId'
    | '/staff/new'
    | '/system/staff'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/billing'
    | '/book'
    | '/calendar'
    | '/conference'
    | '/contact'
    | '/dining'
    | '/gallery'
    | '/guests'
    | '/login'
    | '/lookup'
    | '/portal'
    | '/restaurant'
    | '/rooms'
    | '/system'
    | '/book/confirmation'
    | '/rooms/$roomId'
    | '/staff/new'
    | '/system/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BillingRoute: typeof BillingRoute
  BookRoute: typeof BookRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  ConferenceRoute: typeof ConferenceRoute
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRoute
  GalleryRoute: typeof GalleryRoute
  GuestsRoute: typeof GuestsRoute
  LoginRoute: typeof LoginRoute
  LookupRoute: typeof LookupRoute
  PortalRoute: typeof PortalRoute
  RestaurantRoute: typeof RestaurantRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SystemRoute: typeof SystemRouteWithChildren
  StaffNewRoute: typeof StaffNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference': {
      id: '/conference'
      path: '/conference'
      fullPath: '/conference'
      preLoaderRoute: typeof ConferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/staff': {
      id: '/system/staff'
      path: '/staff'
      fullPath: '/system/staff'
      preLoaderRoute: typeof SystemStaffRouteImport
      parentRoute: typeof SystemRoute
    }
    '/staff/new': {
      id: '/staff/new'
      path: '/staff/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof StaffNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/book/confirmation': {
      id: '/book/confirmation'
      path: '/confirmation'
      fullPath: '/book/confirmation'
      preLoaderRoute: typeof BookConfirmationRouteImport
      parentRoute: typeof BookRoute
    }
  }
}

interface BookRouteChildren {
  BookConfirmationRoute: typeof BookConfirmationRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookConfirmationRoute: BookConfirmationRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface RoomsRouteChildren {
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

interface SystemRouteChildren {
  SystemStaffRoute: typeof SystemStaffRoute
}

const SystemRouteChildren: SystemRouteChildren = {
  SystemStaffRoute: SystemStaffRoute,
}

const SystemRouteWithChildren =
  SystemRoute._addFileChildren(SystemRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BillingRoute: BillingRoute,
  BookRoute: BookRouteWithChildren,
  CalendarRoute: CalendarRoute,
  ConferenceRoute: ConferenceRoute,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRoute,
  GalleryRoute: GalleryRoute,
  GuestsRoute: GuestsRoute,
  LoginRoute: LoginRoute,
  LookupRoute: LookupRoute,
  PortalRoute: PortalRoute,
  RestaurantRoute: RestaurantRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SystemRoute: SystemRouteWithChildren,
  StaffNewRoute: StaffNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
